# Generated by Django 5.0.4 on 2024-04-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='score',
            field=models.FloatField(default=0, null=True),
        ),
    ]
